services:
    mtonzar\\SharedHealthCheckBundle\\DataProvider\\HealthCheckProvider:
        arguments:
            $databaseChecker: '@mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\DatabaseHealthChecker'
            $cacheChecker: '@mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\CacheHealthChecker'
            $queueChecker: '@mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\QueueHealthChecker'
            $apiDependencyChecker: '@mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\ApiDependencyHealthChecker'
        tags: ['api_platform.state_provider']

    mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\DatabaseHealthChecker: ~
    mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\CacheHealthChecker: ~
    mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\QueueHealthChecker: ~
    mtonzar\\SharedHealthCheckBundle\\Service\\HealthChecker\\ApiDependencyHealthChecker: ~
