# SharedServicesBundle/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # HealthCheckers
    mtonzar\SharedServicesBundle\Service\HealthChecker\DatabaseHealthChecker: ~
    mtonzar\SharedServicesBundle\Service\HealthChecker\CacheHealthChecker: ~
    mtonzar\SharedServicesBundle\Service\HealthChecker\QueueHealthChecker: ~
    mtonzar\SharedServicesBundle\Service\HealthChecker\ApiDependencyHealthChecker: ~
    mtonzar\SharedServicesBundle\Service\HealthChecker\LivenessHealthChecker: ~
    mtonzar\SharedServicesBundle\Service\HealthChecker\ReadinessHealthChecker: ~

    # Multi-service checker
    mtonzar\SharedServicesBundle\Service\HealthChecker\MultiServiceHealthChecker: 
        arguments:
            $services: []