services:
    mtonzar\SharedServicesBundle\Provider\HealthCheckProvider:
        arguments:
            $databaseChecker: '@mtonzar\SharedServicesBundle\Service\HealthChecker\DatabaseHealthChecker'
            $cacheChecker: '@mtonzar\SharedServicesBundle\Service\HealthChecker\CacheHealthChecker'
            $queueChecker: '@mtonzar\SharedServicesBundle\Service\HealthChecker\QueueHealthChecker'
            $apiDependencyChecker: '@mtonzar\SharedServicesBundle\Service\HealthChecker\ApiDependencyHealthChecker'
            $livenessChecker: '@mtonzar\SharedServicesBundle\Service\HealthChecker\LivenesHealthChecker'
        tags: ['api_platform.state_provider']

    mtonzar\SharedServicesBundle\Service\HealthChecker\DatabaseHealthChecker:
        autowire: true
        public: true

    mtonzar\SharedServicesBundle\Service\HealthChecker\CacheHealthChecker:
        autowire: true
        public: true

    mtonzar\SharedServicesBundle\Service\HealthChecker\QueueHealthChecker:
        autowire: true
        public: true

    mtonzar\SharedServicesBundle\Service\HealthChecker\ApiDependencyHealthChecker:
        autowire: true
        public: true

    mtonzar\SharedServicesBundle\Service\HealthChecker\LivenessHealthChecker:
        autowire: true
        public: true